version: '3'
services:

  client:
    image: distributed
    restart: always
    build: ./
    links:
      - gather-server
    command: ["client/client", "gather-server:7777"]

  gather-server:
    image: distributed
    restart: always
    build: ./
    expose:
      - "7777"
    links:
      - server
    command: ["gather-server/gather-server", "7777", "server:7778"]

  server:
    image: distributed
    restart: always
    build: ./
    deploy:
      mode: replicated
      replicas: 6
    expose:
      - "7778"
    command: ["server/server", "7778"]

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    links:
      - client

